### ISSUE TITLE
Any plans for newer Boost version, e.g. 1.62?

### ISSUE THREAD

**Issue by adishavit** [arielm/chronotext-boost#3]
Great project! 👍 

Are there any plans for upgrading to a higher version of Boost?

**Comment by arielm** [comment]
Hi,

It requires some work. Will take a look at it during the week-end...

Out of curiosity: what's new in 1.62 compared to 1.58?

**Comment by adishavit** [comment]
Cool! 
There are several new libraries and lots of updates to existing ones.
See:

- http://www.boost.org/users/history/version_1_59_0.html
- http://www.boost.org/users/history/version_1_60_0.html
- http://www.boost.org/users/history/version_1_61_0.html
- http://www.boost.org/users/history/version_1_62_0.html
- http://www.boost.org/users/history/version_1_63_0.html (beta, upcoming version)

**Comment by arielm** [comment]
Thanks for the info.

**Comment by arielm** [comment]
Here we go: [branch 1.62](https://github.com/arielm/chronotext-boost/tree/1.62) is in place

**Comment by adishavit** [comment]
Fabulous! Happy Holidays!
